apps/cadastro/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from cadastro.views import PreparoListView,TachadaListView

app_name = 'cadastro'
urlpatterns = [
    path('preparo/adicionar', views.NovoPreparo,name='novo_preparo'),
    path('tachadas/add_tachada', views.NovaTachada,name='nova_tachada'),
    path('preparos/', PreparoListView.as_view(),name='lista_preparo'),
    path('tachadas/', TachadaListView.as_view(),name='lista_tachada'),
    path('edita/<int:id_tachada>/', views.edit_tachada,name='edita_tachada'),
    path('delete/<int:id_tachada>/', views.delete_tachada,name='delete_tachada'),
   
]

apps/core/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'core'

urlpatterns = [
    path('', views.home,name='home'),
   
]

preparo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('cadastro/',include('cadastro.urls',namespace='cadastro')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cadastro/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Preparo(models.Model):
    data_inicio = models.DateField('Data do preparo',auto_now=False, auto_now_add=False)
    dirigente = models.CharField('M.Dirigente',max_length=100)
    assistente = models.CharField('M.Assistente',max_length=100)
    total_mariri = models.DecimalField('Total mariri',decimal_places=1,max_digits=5)
    total_chacrona = models.DecimalField('Total chacronai',decimal_places=1,max_digits=5)
    mariri_panela = models.DecimalField('Mariri/Panela',decimal_places=1,max_digits=5)
    chacrona_panela = models.DecimalField('Cacrona/Panela',decimal_places=1,max_digits=5)
    observacoes = models.TextField('Observações',max_length=250,blank=True)
    usuario = models.ForeignKey(User,on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Preparo'
        verbose_name_plural = 'Preparos'
        ordering = ['id']
     
    def __str__(self):
        return self.dirigente


class tipo_tachada(models.Model):
    tipo = models.CharField('Tipo Tachada',max_length=30)

    class Meta:
        verbose_name = 'tipo_tachada'
        ordering = ['id']
     
    def __str__(self):
        return self.tipo



class Tachada(models.Model):
    total_mariri = models.DecimalField('Total Mariri',decimal_places=1,max_digits=5,blank=False)
    total_chacrona = models.DecimalField('Total Chacrona',decimal_places=1,max_digits=5,blank=False)
    mariri_panela = models.DecimalField('Mariri/Panela',decimal_places=1,max_digits=5,blank=True)
    chacrona_panela = models.DecimalField('Chacrona/Panela',decimal_places=1,max_digits=5,blank=True)
    num_tachada = models.IntegerField('Num. Tachada',blank=False)
    qtde_panelas = models.IntegerField('Num. Panelas',blank=False)
    hora_entrada = models.TimeField('Hora Entrada',auto_now=False, auto_now_add=False,blank=False)
    hora_fervura = models.TimeField('Hora Fervura',auto_now=False, auto_now_add=False,blank=True)
    hora_saida = models.TimeField('Hora Saída',auto_now=False, auto_now_add=False,blank=True)
    agua_panela = models.DecimalField('Total água',decimal_places=1,max_digits=5,blank=True)
    litros_vegetal = models.DecimalField('Litros Vegetal',decimal_places=1,max_digits=5,blank=True)
    observacoes = models.TextField('Observações',max_length=250,blank=True)
    tipo = models.ForeignKey(tipo_tachada,on_delete = models.CASCADE)
    preparo = models.ForeignKey(Preparo,on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Tachada'
        verbose_name_plural = 'Tachadas'
        ordering = ['id']
     
    def __str__(self):
        return str(self.hora_entrada)

apps/core/models.py
from django.db import models

# Create your models here.

apps/cadastro/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Preparo,Tachada,tipo_tachada
from bootstrap_datepicker_plus import DatePickerInput


class PreparoForm(forms.ModelForm):
    data_inicio = forms.DateField(widget=DatePickerInput(format='%d/%m/%Y'))
    class Meta:
        model = Preparo
        exclude = ('usuario',)


class TachadaForm(forms.ModelForm):

    class Meta:
        model = Tachada
        fields = '__all__'
        

apps/cadastro/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic import ListView
from .models import Preparo,Tachada
from decimal import Decimal
from django.http import JsonResponse


from .forms import PreparoForm,TachadaForm




class PreparoListView(ListView):
    model = Preparo
    template_name = 'preparo/listapreparos.html'
    
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.all()
        #(\usuario=self.request.user)


def NovoPreparo(request):
    template_name = 'preparo/novo_preparo.html'
    context = {}
    if request.method == 'POST':
        form = PreparoForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.usuario = request.user
            f.save()
            messages.success(request, 'Dados gravados com sucesso')
    form = PreparoForm()
    context['form'] = form
    return render(request, template_name, context)


def NovaTachada(request):
    template_name = 'preparo/novaTachada.html'
    context = {}
    if request.method == 'POST':
        form = TachadaForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            total_mariri = Decimal(request.POST.get('total_mariri'))
            total_chacrona = Decimal(request.POST.get('total_chacrona'))
            mariri_panela = Decimal(request.POST.get('mariri_panela'))
            chacrona_panela =Decimal(request.POST.get('chacrona_panela'))
            num_panelas = int(request.POST.get('qtde_panelas'))
            data = confereTachada(mariri_panela,chacrona_panela,num_panelas,total_mariri,total_chacrona)
            f.total_mariri = data[0]
            f.total_chacrona = data[1]
            f.save()
            messages.success(request, 'Dados gravados com sucesso')
        print(form.errors)
        
    
    obj = Preparo.objects.latest('id')
    print(obj)
    obj2 = validaTachada(obj)
    

    if obj2 is not None:
        form = TachadaForm(initial={'total_mariri':obj2.total_mariri,'total_chacrona':obj2.total_chacrona,'preparo':obj2.preparo,'num_tachada':obj2.num_tachada+1})
        context['form'] = form
        return render(request,template_name,context)

    else:
        form = TachadaForm(initial={'total_mariri':obj.total_mariri,'total_chacrona':obj.total_chacrona,'preparo':obj.dirigente,'num_tachada':1})
        context['form'] = form
        return render(request,template_name,context)


def edit_tachada(request, id_tachada):
    template_name = 'preparo/novaTachada.html'
    context = {}
    tachada = get_object_or_404(Tachada, id=id_tachada)
    if request.method == 'POST':
        form = TachadaForm(request.POST, instance=tachada)
        if form.is_valid():
            form.save()
            return redirect('cadastro:lista_tachada')
    form = TachadaForm(instance=tachada)
    context['form'] = form
    return render(request, template_name, context)

def delete_tachada(request, id_tachada):
    pass



class TachadaListView(ListView):
    model = Tachada
    context_object_name = 'tachadas'   # your own name for the list as a template variable
    queryset = Tachada.objects.all()
    template_name = 'preparo/listatachadas.html'  # Specify your own templ


def validaTachada(obj):
    obj2 = int(Tachada.objects.filter(preparo=obj.id).count())
    if obj2 != 0:
       obj2 = Tachada.objects.filter(preparo=obj.id).latest('id')
       return obj2
    return None


def confereTachada(mariri,chacrona,panelas,total_mariri,total_chacrona):
    if mariri is not None  and chacrona is not None:
        total_mariri -= (panelas * mariri)
        total_chacrona -= (panelas * chacrona)
        data = [total_mariri,total_chacrona]
        return data
    



    

apps/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    template_name = 'index.html'
    return render(request, template_name,{})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap-4.5.0.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    
    
 

    <!-- END TEMPUS DOMINUS-->
   
    
    <title>{% block title %} TodoApp {% endblock title %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">SIGEP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample07">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
          <div class="dropdown-menu" aria-labelledby="dropdown07">
            <a class="dropdown-item" href="{% url 'cadastro:novo_preparo' %}">Novo Preparo</a>
            <a class="dropdown-item" href="{% url 'cadastro:lista_preparo' %}">Listar Preparos</a>
            <a class="dropdown-item" href="{% url 'cadastro:nova_tachada' %}">Nova Tachada</a>
            <a class="dropdown-item" href="{% url 'cadastro:lista_tachada' %}">Lista Tachada</a>
            
          </div>
        </li>
      </ul>
      
     
        <ul class="navbar-nav">
          <li class="nav-item">
           
              
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="#">Perfil</a>
              <a class="dropdown-item" href="#">Trocar senha</a>
              <a class="dropdown-item" href="#">Outras informações</a>
              <a class="dropdown-item" href="#">Sair</a>
            </div>
          </li>
        </ul>
      
    </div>
  </div>
</nav>

    {% block body %}

    
    {% endblock body %}
 
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'js/mask.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/bootstrap-4.5.0.min.js' %}"></script>
    <script>
        $(document).on('click', '.confirm-delete', function() {
          $('#confirmDeleteModal').attr('caller-id', $(this).attr('id'));
        });
        $(document).on('click', '#confirmDeleteButtonModal', function() {
          var caller = $('#confirmDeleteButtonModal').closest('.modal').attr('caller-id');
          window.location = $('#'.concat(caller)).attr('href');
        });
        $(function() {
          $('#id_end_date').datepicker(
            {
              dateFormat: "dd/mm/yy",
              dayNamesMin: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
              monthNames: ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]
            }
          );
        });
        $(document).ready(function() {
          $('#id_category').select2();
        });

        
            $(function () {
                $('.input-group').attr('id', 'datetimepicker1');
                $('#datetimepicker1').datetimepicker({
                  format:'DD/MM/YYYY',
                  locale:'pt-br'
                });
            });
       

         
           
        
      
            
  </script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    {{ block.super }}
{% endblock title %}

templates/novoPreparo.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Adicionar Categoria - {{ block.super }}

{% endblock title %}


{% block body %}
    <div class="container">
        <h1>Categoria</h1>
        {% include 'partials/messages.html' %}
        <div class="row">
            <div class="col-md-12">
                <form action="." method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Nome</label>
                    {{ form.name|add_class:"form-control"|attr:"autofocus" }}e
                </div>
                <div class="form-group">
                    <label for="{{ form.description.id_for_label }}">Descrição</label>
                    {{ form.description|add_class:"form-control" }}
                </div>

                <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>


{% endblock body %}
    

templates/partials/confirm_delete_modal.html
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body confirm-delete">
          Esta ação é definitiva! Tem certeza que deseja continuar?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteButtonModal">Excluir</button>
        </div>
      </div>
    </div>
</div>

templates/partials/footer.html
<!-- Footer -->
<footer class="page-footer font-small special-color-dark pt-4">

  <!-- Footer Elements -->
  <div class="container">

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!-- Form -->
        <form class="form-inline">
          <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search"
            aria-label="Search">
          <i class="fas fa-search" aria-hidden="true"></i>
        </form>
        <!-- Form -->

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <form class="input-group">
          <input type="text" class="form-control form-control-sm" placeholder="Your email"
            aria-label="Your email" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-sm btn-outline-white my-0" type="button">Sign up</button>
          </div>
        </form>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
  <!-- Footer Elements -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}
    

templates/preparo/listapreparos.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}

    Novo Preparo - {{ block.super }}

{% endblock title %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
        <h1>Lista de Preparos</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Data</th>
                    <th scope="col">Dirigente</th>
                    <th scope="col">Assistente</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <th scope="row">{{ object.id }}</th>
                    <td>{{ object.data_inicio }}</td>
                    <td>{{ object.dirigente }}</td>
                    <td>{{ object.assistente }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </div>
    </div>
</div>

{% endblock%}

templates/preparo/listatachadas.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}

   Lista de Tachadas - {{ block.super }}

{% endblock title %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
        <h1>Lista de Tachadas</h1>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tipo</th>
                    <th scope="col">Entrada</th>
                    <th scope="col">Fervura</th>
                    <th scope="col">Saída</th>
                    <th scope="col">Lts</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for tachada in tachadas %}
                <tr>
                    <td scope="row">{{ tachada.num_tachada }}</td>
                    <td scope="row">{{ tachada.tipo }}</td>
                    <td scope="row">{{ tachada.hora_entrada }}</td>
                    <td scope="row">{{ tachada.hora_fervura }}</td>
                    <td scope="row">{{ tachada.hora_saida }}</td>
                    <td scope="row">{{ tachada.litros_vegetal }}</td>
                    <td>
                        <a href="{% url 'cadastro:edita_tachada' tachada.id %}" class="btn btn-primary btn-sm">Editar</a>
                        <a href="{% url 'cadastro:delete_tachada' tachada.id %}" class="btn btn-danger btn-sm confirm-delete" data-toggle="modal", data-target="#confirmDeleteModal" id="deleteButton-{{ tachada.id }}">Excluir</a>
                    </td>
                    
                    
                </tr>
                {% endfor %}
            </tbody>
        </div>
    </div>
    {% include 'partials/confirm_delete_modal.html' %}
</div>

{% endblock%}

templates/preparo/novaTachada.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Novo Preparo - {{ block.super }}

{% endblock title %}

{% block body %}
{{form.media}}
<div class="container">
    <h2>Nova Tachada</h2>
    {% include 'partials/messages.html' %}
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}

              
                <div class="form-group col-md-5">
                    <label for="{{ form.total_mariri.id_for_label }}">Num. Tachada</label>
                    {{form.num_tachada |add_class:"form-control" |attr:"readonly" }}
                     
                </div>
                <div class="form-group col-md-5">
                    <label for="{{ form.total_mariri.id_for_label }}">Total Mariri</label>
                    {{form.total_mariri |add_class:"form-control"   |attr:"readonly"}}
                     
                </div>
                
                <div class="form-group col-md-5">
                    <label for="{{ form.total_chacrona_for_label }}">Total chacrona</label>
                    {{form.total_chacrona |add_class:"form-control"  |attr:"readonly" }}
                     
                </div> 
                 
                <div class="form-group col-md-5">
                    <label for="{{ form.mariri_panela_for_label }}">Mariri/panela</label>
                    {{form.mariri_panela |add_class:"form-control" }}
                     
                </div> 
                 
                <div class="form-group col-md-5">
                    <label for="{{ form.chacrona_panela_for_label }}">Chacrona/Panela</label>
                    {{form.chacrona_panela |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-5">
                    <label for="{{ form.qtde_panelas.id_for_label }}">Num. Panelas:</label>
                    {{form.qtde_panelas |add_class:"form-control"  |attr:"required" }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.hora_entrada.id_for_label }}">Hora Entrada</label>
                    {{form.hora_entrada |add_class:"form-control"  |attr:"required" }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.hora_fervura.id_for_label }}">Hora fervura</label>
                    {{form.hora_fervura |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.hora_saida.id_for_label }}">Hora saída</label>
                    {{form.hora_saida |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.agua_panela.id_for_label }}">Água/panela:</label>
                    {{form.agua_panela |add_class:"form-control"  }}
                     
                </div> 
                
                <div class="form-group col-md-2">
                    <label for="{{ form.litros_vegetal.id_for_label }}">Vegetal(Lts):</label>
                    {{form.litros_vegetal |add_class:"form-control"  }}
                     
                </div> 
               
                <div class="form-group col-md-2">
                    <label for="{{ form.tipo.id_for_label }}">Tipo Tachada:</label>
                    {{form.tipo |add_class:"form-control" |attr:"required"   }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.preparo.id_for_label }}">Dirigente:</label>
                    {{form.preparo |add_class:"form-control" |attr:"required"  }}
                     
                </div> 
                <div class="form-group col-md-6">
                    <label for="{{ form.observacoes.id_for_label }}">Observações:</label>
                    {{form.observacoes |add_class:"form-control"  }}
                     
                </div> 
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/preparo/novo_preparo.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}

    Novo Preparo - {{ block.super }}

{% endblock title %}

{% block body %}
{{form.media}}
<div class="container">
    <h2>Novo Preparo</h2>
    {% include 'partials/messages.html' %}
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post" autocomplete="off">
                {% csrf_token %}
                <div class="form-group col-md-5">
                    <label for="{{ form.data_inicio.id_for_label }}">Data de Início:</label>
                    {{form.data_inicio |add_class:"form-control"  }}
                     
                </div>
                
                
                <div class="form-group col-md-5">
                    <label for="{{ form.dirigente.id_for_label }}">M. Dirigente</label>
                    {{form.dirigente |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-5">
                    <label for="{{ form.assistente.id_for_label }}">M. Assistente:</label>
                    {{form.assistente |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.total_mariri.id_for_label }}">Total mariri:</label>
                    {{form.total_mariri |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.total_chacrona.id_for_label }}">Total Chacrona:</label>
                    {{form.total_chacrona |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.mariri_panela.id_for_label }}">Mariri/Panela:</label>
                    {{form.mariri_panela |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-2">
                    <label for="{{ form.chacrona_panela.id_for_label }}">Chacrona/Panela:</label>
                    {{form.chacrona_panela |add_class:"form-control"  }}
                     
                </div> 
                <div class="form-group col-md-6">
                    <label for="{{ form.observacoes.id_for_label }}">Observações:</label>
                    {{form.observacoes |add_class:"form-control"  }}
                     
                </div> 
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}